In [ ]:
# Import needed libraries
import pandas as pd
from sqlalchemy import create_engine

# Connect to the db we created
Engine = create_engine("sqlite:///..//data/processed/football_scouting.db")

# Read the whole Match_Metrics table into a DataFrame (the "league" for comparisons)
league_df = pd.read_sql("SELECT * FROM Match_Metrics", Engine)

print("Rows and Columns: ", league_df.shape)
league_df.head()

# MISSING DATA

Rows and Columns:  (275, 16)

,match_id,player_id,player_name,position,total_passes,total_completed_passes,total_accuracy_passes,total_progressive_passes,total_long_passes,total_won_duels,total_duels,total_successful_interceptions,total_recoveries,total_tackles_won,minutes_played,rating
0,8650,2954,Youri Tielemans,Left Center Midfield,1,1,None,0,None,0,0,0,0,None,None,None
1,8650,3054,Fernando Luiz Roza,Center Midfield,66,57,None,9,None,0,1,2,7,None,None,None
2,8650,3077,Jan Vertonghen,Left Back,47,40,None,8,None,0,3,0,2,None,None,None
3,8650,3089,Kevin De Bruyne,Secondary Striker,42,33,None,13,None,1,1,0,10,None,None,None
4,8650,3101,Vincent Kompany,Left Center Back,44,41,None,8,None,1,1,0,1,None,None,None

In [5]:
# How many empty values do we have?
print(league_df.isna().sum())

# Basic Stats of every numeric column
league_df.describe()

match_id                            0
player_id                           0
player_name                         0
position                            0
total_passes                        0
total_completed_passes              0
total_accuracy_passes             275
total_progressive_passes            0
total_long_passes                 275
total_won_duels                     0
total_duels                         0
total_successful_interceptions      0
total_recoveries                    0
total_tackles_won                 275
minutes_played                    275
rating                            275
dtype: int64

,match_id,player_id,total_passes,total_completed_passes,total_progressive_passes,total_won_duels,total_duels,total_successful_interceptions,total_recoveries
count,275.000000,275.000000,275.000000,275.000000,275.000000,275.000000,275.000000,275.000000,275.000000
mean,7655.920000,5219.141818,35.749091,29.294545,7.818182,0.596364,1.610909,0.483636,3.120000
std,328.859355,1921.710398,24.284633,21.915160,6.939496,0.888278,1.638238,0.816518,2.438319
min,7534.000000,2941.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,7539.000000,4611.500000,18.000000,13.000000,2.000000,0.000000,0.000000,0.000000,1.000000
50%,7544.000000,5542.000000,32.000000,24.000000,6.000000,0.000000,1.000000,0.000000,3.000000
75%,7554.000000,5629.000000,50.000000,41.000000,11.000000,1.000000,3.000000,1.000000,4.500000
max,8650.000000,20005.000000,113.000000,104.000000,47.000000,4.000000,9.000000,5.000000,13.000000

In [6]:
# How many rows do we have for each position?
league_df['position'].value_counts()

position
Left Center Midfield         25
Left Center Back             23
Right Center Midfield        23
Left Wing                    22
Right Wing                   20
Right Center Back            20
Goalkeeper                   20
Left Back                    19
Right Back                   18
Center Forward               17
Center Attacking Midfield    13
Left Center Forward           8
Right Midfield                7
Left Midfield                 6
Right Center Forward          5
Center Defensive Midfield     5
Secondary Striker             4
Left Defensive Midfield       4
Center Back                   3
Left Wing Back                3
Right Defensive Midfield      3
Center Midfield               2
Right Wing Back               2
Right Attacking Midfield      2
Left Attacking Midfield       1
Name: count, dtype: int64

In [8]:
# Match detailed position to a broad group (Midfilder, Defender, Forward)
def get_position_group(position):
    if position is None:
        return None
    if position == "Goalkeeper":
        return "Goalkeeper"
    if "Back" in position:
        return "Defender"
    if "Midfield" in position:
        return "Midfielder"
    return "Forward"

league_df["position_group"] = league_df["position"].apply(get_position_group)
league_df["position_group"].value_counts()

position_group
Midfielder    91
Defender      88
Forward       76
Goalkeeper    20
Name: count, dtype: int64

In [10]:
# Import needed libraries
import plotly.express as px

fig = px.box(
    league_df,
    x = "position_group",
    y = "total_progressive_passes",
    title = "Progressive passes per player per match, by position gorup!"
)

fig.show()